import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "@styles/main.scss"
import { Header } from "@components/header/Header"
import { Footer } from "@components/Footer"
import { Toaster } from "sonner"
import { AppWrapper } from "@context/MainContext"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="cs">
      <AppWrapper>
        <body className="flex justify-between min-h-screen flex-col">
          <Header />
          <div className="flex-grow flex items-center lg:mt-10 mt-20">
            {children}
          </div>
          <Toaster richColors closeButton />
          <Footer />
        </body>
      </AppWrapper>
    </html>
  )
}
